name: CI/CD

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential cmake g++ libomp-dev

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install pytest numpy pybind11
          # Make sure pybind11 is properly installed for CMake to find
          pip install pybind11[global]
          # Install the package in development mode
          pip install -e .

      - name: Build C++ extension
        env:
          CI: true
        run: |
          mkdir -p build
          cd build
          # Set the CMAKE_PREFIX_PATH to help find pybind11
          cmake .. -DCMAKE_PREFIX_PATH=$(python -c "import pybind11; print(pybind11.get_cmake_dir())")
          cmake --build . --config Release
          cd ..

      # run tests
      - name: Test with pytest
        run: |
          pytest tests/
